---
server:
  port: 8080
  
JWT:
  secretKey: ZGV2ZVNlckdyYW5kZUFDaGF2ZQ==

host:
  api:
    github: https://api.github.com/user/repos?per_page=1000
  
spring:
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true 
    serialization: 
      indent-output: true
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
    default-property-inclusion: non-empty 
    